- NumPy - numerical operations
- Pandas - deal with data manipulation
- Matplotlib - plotting library
- Scikit-learn - machine learning
- Tensorflow or PyTorch - are frameworks for deep learning

## NumPy

- Numerical Python - Num Py
- gives us a fast data type - called Array or `ndarray` -> N-Dimensional Array
- Numpy helps us do math on arrays
    - Data science and analytics?, how it helps?
    - Store data in arrays
    - Implement statistics or other operations
    - Matrix operations - can help in tables, ML and also DL
- numpy is one of the most fundamental libraries in python
- 
- there used to be a disscussion on whether to put numpy inside of python by default
    - creators of python thought that would be too much code to handle 
    - 
- [Learn Numpy from Documentation](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [11]:
#pip install numpy

- Everything we covered so far, was to teach you python and programming
    - is so that you can learn things on you own later
- 

## Arrays
- Array is a homogenous and linear data structure 
    - homogeous - you save `only one type of data` elements inside
    - it has indicies - we can use them to access data
    - Contigous blocks of memory - every element comes one after the other
        - Unlike lists, where every element is scattered through the memory
- if we already have lists in python, why do we need Arrays?
    - Arrays are very **FAST** compared to list
        - reason is not just how numpy was created, but also the fact that we only store single type of data inside arrays
        - 
- Numpy arrays are better at numerical operation than python lists ---> because of **BROADCASTING**

In [2]:
import numpy as np

# simple array

num_list = [1,2,3,4,5] # python list
num_array = np.array(num_list)  # python list as argument to the array() method
print(num_array)   # [1 2 3 4 5]

num_array # array([1, 2, 3, 4, 5])

# print(num_list) #[1, 2, 3, 4, 5]

# type(num_array) # numpy.ndarray

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [3]:
# homogenity of arrays

num_list = [1, 2.0,"idrees", 4, 5]    # multiple types of data

num_array = np.array(num_list)  # array will lose its special powers
# you can create an array like this
# dtype='<U32' ---> this data type says that --- this array won't be as fast
# array will lose its special powers of speed and memory optimization


# this is worse than a list

num_array


array(['1', '2.0', 'idrees', '4', '5'], dtype='<U32')

In [14]:
num_list = [1,2,3,4,5,6,7,8,9]     # [10,20,30,40,50,60,70,80,90]
num_list10 = []

for num in num_list:
     num_list10.append(num*10)


num_list10 = [x*10 for x in num_list]
print(num_list10)

[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [15]:
# Broadcasting

num_array = np.array(num_list)
num_array   # array([1, 2, 3, 4, 5, 6, 7, 8, 9])

num_array * 10


# no need of the for loop for Numpy arrays

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

- This is called **BROADCASTING**
    - one of the special things about Numpy
    - Broadcasting means taking an array and operating it with another
        - following a one to one operation
        - every element operated with another 


- numpy lets us do numerical operations really well

In [ ]:
num_4 = np.array([1, 2, 3, 4])
num_3 = np.array([10, 10, 20])

#num_3 * num_4 # Error: operands could not be broadcast together with shapes (3,) (4,)

List | Array
----|-----
store pointers(addresses of the data) | Store actual data
objects are scattered through the memory | are Contigous (one after the other)
CPU has to go to each object address to access data | CPU accesses base address and then adds e.g. 8 to that address to get the next element
Heterogenous, every object of different type | Homogenous. Multiple types are not allowed
every object has some extra baggage like data type information | dtype of an entire array is same
Broadcasting is not allowed | Broadcasting can be done

- you won't be able to notice too much difference untill you don't have 1000s of elements to deal with
- untill the data to deal with is huge, you will not notice how arrays are life savers

### Shapes and Dimensions

1D array :

2D array :

3D array : 

...

### Exercise:  (understand performance difference between the two)

1. Create a python List ---> `N = 10000` then `listname = list(range(N))`
2. Create an numpy array
3. We observe the size of both ---> use the `sys` module and `sys.getsizeof()`
4. Use time module to time the amount of time taken to do multiplication
    - `start_time = time.time() # current time`
    - your list *2 ---> execute this 
    - end_time = time.time()
    - list_time = end_time - start_time ---> amount of time took for a list to multiply 2 with all the members
5. Repeat the step 4 with a array - But simply multiply the array with the list

If not much difference please increase `N` to 1000000000

In [29]:

pylist = [100,200,300]

print(id(pylist)) # where is the pylist variable saved
print(id(pylist[0])) # location/address of the first element
print(id(pylist[1]))
print(id(pylist[2]))

135654491561216
99143382667272
99143382670472
135654492867568


In [30]:
np_arr = np.array([100,200,300,400], dtype= np.int64)
np_arr.ctypes.data # base address


99144146398880

In [ ]:
import numpy as np

# A NumPy array of 64-bit integers (8 bytes each)
np_arr = np.array([100, 101, 102], dtype=np.int64)

print("--- NumPy Array Memory ---")
print(f"Base memory address: {np_arr.ctypes.data}")
print(f"Step size (strides): {np_arr.strides}") 

# Let's calculate the address of each element manually
base = np_arr.ctypes.data

for i in range(len(np_arr)):
    print(f"Element {i} address: {base + (i * 8)}")

--- NumPy Array Memory ---
Base memory address: 99144148341504
Step size (strides): (8,)
Element 0 address: 99144148341504
Element 1 address: 99144148341512
Element 2 address: 99144148341520
