# Pandas
- python library
- fast, powerful, flexible and easy to use open source data **analysis** and **manipulation** tool
- provides Series and Dataframe objects
- These objects are use to store and manipulate structured data (data in tabular form)
- 
- pandas comes from `Panel Data`
- `Python for Data Analysis`
- `s` refers to the series object


In [2]:
#pip install pandas

In [3]:
import pandas as pd

### Core Objects
- Series - is a one dimensional labelled array (like a single column)
    - series = one column
- DataFrame - a two-dimensional table made of multiple series of same index
    - dataframe = a sheet of columns and rows

In [4]:
maths = pd.Series([20, 30, 40], dtype = 'int8', name = 'math')
type(maths) # pandas.Series

print(maths)



0    20
1    30
2    40
Name: math, dtype: int8


In [5]:
english = pd.Series([20, 30, 40])
python = pd.Series([20, 55, 40])
science = pd.Series([20, 99, 40])

In [6]:
pd.concat([maths,english, python, science]) # series object
df = pd.concat([maths,english, python, science], axis = 1)

type(df)

pandas.core.frame.DataFrame

In [7]:
# dataframe from dictionary of Lists  --- each list has to be of same size
data = {
    "Students": ["Nomie", "Idrees", "Radia"],
    "Maths": [85, 95, 90],
    "English": [75, 85 , 80],
}

df = pd.DataFrame(data)
df

,Students,Maths,English
0,Nomie,85,75
1,Idrees,95,85
2,Radia,90,80


In [8]:
# dataframe from List of Dictionaries --- each dictionary can be of different size
# we can miss elements --- those elements will appear as NaN values

data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'London'},
    {'Name': 'Charlie', 'Age': 35}
]

df = pd.DataFrame(data)
df

,Name,Age,City
0,Alice,25,New York
1,Bob,30,London
2,Charlie,35,NaN


- NaN values
    - Not a Number
    - aka Missing Values

In [9]:
# dataframe from 2D arrays
data = [
    ['Alice', 25, 'New York'],
    ['Bob', 30, 'London'],
    ['Charlie', 35, 'Paris']
]

# We must explicitly define columns here
df = pd.DataFrame(data, columns=['Name', 'Age', 'City'], )
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris


Series has:
- Index
- Name

DataFrame will have:
- Header - is the names of columns
    - `pd`.`DataFrame`(file, `columns` = ["col1", "col2", "col3"])
- Index - 
    - `pd`.`DataFrame`(file, `columns` = ["col1", "col2", "col3"], `index` = [1,2,3])
    - index_col = "column name" ===> argument we can pass as well
    - df.set_index("column name")

#### Mini-Activity:

> 1. Create a `pd.Series` with 5 temperature values and print it.

> 2. Create a pd.DataFrame with columns "`City`" and "`Temperature`" for 3 cities.

> 3. Check the `type()` of each object you created.

> 4. Add a name to your Series and print it again.

### Reading from and writing to a CSV files
- pd.read_csv()

In [11]:
# DataFrames from Files

# From a CSV file
# df_csv = pd.read_csv('my_data.csv')

# From an Excel file
# df_excel = pd.read_excel('my_data.xlsx')

# From a JSON file or API response
# df_json = pd.read_json('my_data.json')

In [12]:
# Let's create a sample CSV file first, then read it
sample_data = """Name,Department,Salary,Experience
Alice,Engineering,75000,3
Bob,Marketing,65000,5
Charlie,Engineering,80000,7
Diana,HR,60000,2
Eve,Marketing,70000,4"""

with open("employee.csv", 'w') as f:
    f.write(sample_data)   

In [13]:
df = pd.read_csv("employee.csv")
df

,Name,Department,Salary,Experience
0,Alice,Engineering,75000,3
1,Bob,Marketing,65000,5
2,Charlie,Engineering,80000,7
3,Diana,HR,60000,2
4,Eve,Marketing,70000,4


In [16]:
# Dataframe for the Previou Scenario Exercise

import numpy as np
np.random.seed(42)
 
#2.
results = np.random.randint(0,101, (10,3))
print("--- Results ---")
print(results)

df_results = pd.DataFrame(results, columns = ["maths", "english","science"])

df_results.to_csv("student_marks.csv", index = False) # it excludes the index

--- Results ---
[[51 92 14]
 [71 60 20]
 [82 86 74]
 [74 87 99]
 [23  2 21]
 [52  1 87]
 [29 37  1]
 [63 59 20]
 [32 75 57]
 [21 88 48]]


In [15]:
df_results

,maths,english,science
0,51,92,14
1,71,60,20
2,82,86,74
3,74,87,99
4,23,2,21
5,52,1,87
6,29,37,1
7,63,59,20
8,32,75,57
9,21,88,48
